### ISSUE TITLE
add_rfree() does not consider Friedel mates

### ISSUE THREAD

**Issue by DHekstra** [rs-station/reciprocalspaceship#215]
Phenix expects matching Rfree flags for Friedel mates (https://phenix-online.org/pipermail/phenixbb/2015-March/021837.html), which is not currently the case in rs.utils.add_rfree.py()

**Comment by JBGreisman** [comment]
To better understand your use case, do you mind describing more what you are trying to do?

Based on the code, this should handle anomalous data as long as it is provided in 2-column format. If provided in 1-column format, each reflection will be treated independently. If this is what is happening in your case, you should be able to use `DataSet.unstack_anomalous(...)` to format your data for use with `rs.utils.add_rfree()`.

This method also doesn't explicitly check that a `DataSet` object holds merged data, but it is also only intended to be used with data for which `DataSet.merged == True`.

**Comment by DHekstra** [comment]
Thanks. That seems a satisfactory solution.
