### ISSUE TITLE
No documentation of CrystFEL columns

### ISSUE THREAD

**Issue by kmdalton** [rs-station/reciprocalspaceship#231]
The [docstring](https://github.com/rs-station/reciprocalspaceship/blob/3809a90c343e9e721dad4fcf0e09b58d8ed8467c/reciprocalspaceship/io/crystfel.py#L217) for `rs.read_crystfel`doesn't say anything about the columns in the dataset which it returns. I suggest the following descriptions as a start:

 - XDET,YDET : internal detector panel coordinates
 - s1x,s1y,s1z : scattered beam wavevector which points from the sample to the bragg peak
 - I, SigI : intensity, uncertainty
 - ewald_offset, angular_ewald_offset : the distance in cartesian space in reciprocal angstroms or polar coordinates in degrees between the observed reflection and the ewald sphere
 - BATCH : the image number

**Comment by JBGreisman** [comment]
@kmdalton Do you think it makes sense to incorporate this into #216 because it already includes planned updates to the implementation?
