### ISSUE TITLE
bug in `is_isomorphous` cell comparison

### ISSUE THREAD

**Issue by tjlane** [rs-station/reciprocalspaceship#277]
The method documentation says:
https://github.com/rs-station/reciprocalspaceship/blob/ceae60e293bfdb3e969d0e3e2b53fa3a2b9e34f9/reciprocalspaceship/dataset.py#L1191-L1192

But the code looks for an absolute change:
https://github.com/rs-station/reciprocalspaceship/blob/ceae60e293bfdb3e969d0e3e2b53fa3a2b9e34f9/reciprocalspaceship/dataset.py#L1217

By default this will return `False` if the cells differ by more than 5 Å or 5 degrees in any case.

I'd suggest we change this to make it relative, as the documentation indicates.

**Comment by kmdalton** [comment]
Can confirm. This is a bug. I like your proposal.

**Comment by kmdalton** [comment]
what's a reasonable default for the `cell_threshold`?  i think 0.5% is in the right ballpark. @tjlane

**Comment by kmdalton** [comment]
fixed in #279
