### ISSUE TITLE
Add Support for Reading DIALS `refl` Files

### ISSUE THREAD

**Issue by kmdalton** [rs-station/reciprocalspaceship#78]
As we discussed extensively on the DIALS Slack channel, it is now relatively easy to parse DIALS `.refl` files without `cctbx/DIALS`. Newer versions of DIALS encode reflection tables using `msgpack` which seems a relatively innocuous dependency to add. 

To this end @ndevenish has built a [parser](https://gist.github.com/ndevenish/079eb17365b21d2044ac146f67dbb499) that decodes refl tables using `numpy`. It's nearly complete but may be missing column types. We can find a full list of types in this [block](https://github.com/dials/dials/blob/17610d74a4804811e262f8164a933dcb11a671f7/array_family/reflection_table_msgpack_adapter.h#L657-L682). It should be easy to build this into the `rs.io` submodule as I've done [here](https://github.com/kmdalton/reciprocalspaceship/blob/refl_file/reciprocalspaceship/io/refl.py) for example. 

There remains the issue of DIALS reflection tables potentially containing some fairly exotic objects (shoeboxes, vectors, matrices). The safest (sadly slowest) thing to do for a first pass is to just default them to objects. We can think about clever solutions later. 

Parsing legacy `pickle` based reflection tables is an open question. For the time being, I think we just can't support them. @ndevenish suggests looking [here](https://github.com/cctbx/cctbx_project/blob/master/scitbx/serialization/base_256.h) for clues though. 

@JBGreisman, let's chat about this early next week and get it up and running. I think this is already mostly there!

**Comment by kmdalton** [comment]
@PrinceWalnut , you may want to help here too.

**Comment by ndevenish** [comment]
I've updated it to handle the missing types, and a basic pytest test (it can be run `refl_loader.py --write-test` inside a cctbx environment to write it's test file). `std::string` is also supposed to be handled by the msgpack writer but is rather broken - https://github.com/dials/dials/issues/1858 - so am pretty sure that's not "in the wild" anywhere.

**Comment by kmdalton** [comment]
wacky. we'll certainly be skipping any string columns for now at least...

**Comment by JBGreisman** [comment]
This looks like a pretty solid start. There are a few columns that _can_ be stored in a `DataFrame`/`DataSet`, but _cannot_ be written to an MTZ file. I think a decision we will have to make is whether those columns should be skipped, or whether they should be parsed and included in the `DataSet`. 

It is always possible to add new dtypes if that would improve the behavior of anything (for strings, pandas already has us covered: [StringDtype](https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html)). It is also possible to add multidimensional numpy arrays as columns, but they seem to really end up more as "lists of arrays"
